//! NCBI codon translation tables.
//! Each table maps 64 codon indices (ordered ACGT at each position) to amino acids.
//! '*' represents a stop codon.

pub static TABLE_1: [u8; 64] = *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSS*CWCLFLF";
pub static TABLE_2: [u8; 64] = *b"KNKNTTTT*S*SMIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLF";
pub static TABLE_3: [u8; 64] = *b"KNKNTTTTRSRSMIMIQHQHPPPPRRRRTTTTEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLF";
pub static TABLE_4: [u8; 64] = *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLF";
pub static TABLE_5: [u8; 64] = *b"KNKNTTTTSSSSMIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLF";
pub static TABLE_6: [u8; 64] = *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVQYQYSSSS*CWCLFLF";
pub static TABLE_9: [u8; 64] = *b"NNKNTTTTSSSSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLF";
pub static TABLE_10: [u8; 64] =
    *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSCCWCLFLF";
pub static TABLE_11: [u8; 64] =
    *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSS*CWCLFLF";
pub static TABLE_12: [u8; 64] =
    *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLSLEDEDAAAAGGGGVVVV*Y*YSSSS*CWCLFLF";
pub static TABLE_13: [u8; 64] =
    *b"KNKNTTTTGSGSMIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLF";
pub static TABLE_14: [u8; 64] =
    *b"NNKNTTTTSSSSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVVYY*YSSSSWCWCLFLF";
pub static TABLE_16: [u8; 64] =
    *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*YLYSSSS*CWCLFLF";
pub static TABLE_21: [u8; 64] =
    *b"NNKNTTTTSSSSMIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLF";
pub static TABLE_22: [u8; 64] =
    *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*YLY*SSS*CWCLFLF";
pub static TABLE_23: [u8; 64] =
    *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSS*CWC*FLF";
pub static TABLE_24: [u8; 64] =
    *b"KNKNTTTTSSKSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSWCWCLFLF";
pub static TABLE_25: [u8; 64] =
    *b"KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSSGCWCLFLF";

/// Get a codon table by NCBI ID (1-25). Returns None for unsupported IDs.
pub fn get_codon_table(id: usize) -> Option<&'static [u8; 64]> {
    match id {
        1 => Some(&TABLE_1),
        2 => Some(&TABLE_2),
        3 => Some(&TABLE_3),
        4 => Some(&TABLE_4),
        5 => Some(&TABLE_5),
        6 => Some(&TABLE_6),
        9 => Some(&TABLE_9),
        10 => Some(&TABLE_10),
        11 => Some(&TABLE_11),
        12 => Some(&TABLE_12),
        13 => Some(&TABLE_13),
        14 => Some(&TABLE_14),
        16 => Some(&TABLE_16),
        21 => Some(&TABLE_21),
        22 => Some(&TABLE_22),
        23 => Some(&TABLE_23),
        24 => Some(&TABLE_24),
        25 => Some(&TABLE_25),
        _ => None,
    }
}
